
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { Noto_Kufi_Arabic, Roboto } from 'next/font/google';
import "./globals.css";
const notoKufiArabic = Noto_Kufi_Arabic({
  weight: "400",
  style: ['normal'],
  subsets: ['arabic'],
  display: 'swap',
});

const roboto = Roboto({
  weight: "400",
  style: ['normal'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
   const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  
  const messages = await getMessages();
  const fontClass = locale === 'ar' ? notoKufiArabic.className : roboto.className;
  return (
    <html lang={locale}>
      <body
        className={` antialiased ${fontClass}`}
      >
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
